### ISSUE TITLE
[FEAT] - Add deepsource

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/we-love-hacktoberfest#155]
### What feature would you like to see?

Add phrase matching for deepsource:

- Add an `deepsource` array to the `src/data/phrases.ts` file with some phrases praising them.
- Add an `isAppwrite.ts` file to the `src/modules` directory and have it match the keyword `deepsource`. (Follow the existing logic, use Hacktoberfest as an example)
- Import the new `isAppwrite` module to the `_moduleList.ts` file and add it to the array.

**Comment by Dominosam** [comment]
Hey, I would like to try myself with this issue

**Comment by nhcarrigan** [comment]
All yours!
