### ISSUE TITLE
[FEAT] - Tag aliases

### ISSUE THREAD

**Issue by MattIPv4** [nhcarrigan/we-love-hacktoberfest#178]
### What feature would you like to see?

As well as the main tag slug, track an array of additional aliased names for each tag.

**Comment by nhcarrigan** [comment]
I like this idea, and will open it up for contribution.

A PR that resolves this issue should:

- Update the `src/interfaces/Tag.ts` interface to have an `aliases: string[];` property.
- Update each tag within the `src/data/tags.ts` file to have an `aliases` property with either an empty array or an array of strings.
- Update the logic in `src/modules/sendTag.ts` to look for a tag where `t.name === target || t.aliases.includes(target)`.
- Update the tests in `tests/data.spec.ts` to:
  - After the `tagNames` declaration, loop through the tags and push the `aliases` to that array.
  - Add a test to assert that each alias is also unique.
