### ISSUE TITLE
[REQUEST] - Additional Phrases

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/we-love-hacktoberfest#2]
# Feature Request

## Is your feature request related to a problem? Please describe:

Currently the bot only says one phrase. Over and over again.

## Describe the solution you'd like

Let's get creative! We can build an array or JSON object with multiple phrases to say and have the bot randomly select one.

**Comment by Vyvy-vi** [comment]
I think this is still a problem.
(most of the statements aren't customised per person) Would be really nice if we could make custom phrases for everyone

**Comment by nhcarrigan** [comment]
Closing as stale.
