### ISSUE TITLE
[BUG] - Not picking up multiple loves when the user is a recipient

### ISSUE THREAD

**Issue by lukeocodes** [nhcarrigan/we-love-hacktoberfest#271]
### What bug did you encounter?

When a user who receives love mentions another user, only the sender's user receives love

![image](https://user-images.githubusercontent.com/956290/149753325-d86a14cd-0514-4e3f-a94c-56a317fa0249.png)

### What did you expect to happen?

I expected it to .join love for me and @nhcarrigan 

### Screenshots

![image](https://user-images.githubusercontent.com/956290/149753325-d86a14cd-0514-4e3f-a94c-56a317fa0249.png)

### Additional information

Nick is great :)

**Comment by nhcarrigan** [comment]
https://github.com/nhcarrigan/we-love-hacktoberfest/blob/c782742e8f93db13766e5c5afbb7ad6147083d7b/src/data/loveData.ts#L65

Bot looks for `nhcarrigan` 🙃

**Comment by lukeocodes** [comment]
Oh, still a bug :P
