### ISSUE TITLE
[DOC] - Add more reasons to the README

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/we-love-hacktoberfest#3]
# Incorrect Documentation

## Describe the error

The readme only has 5 reasons why we love Matt. 

## Expected information

There are **way** more reasons to love Matt. Add your reasons to the README!

**Comment by ish-u** [comment]
Hello,
Can i contribute to this ?

**Comment by nhcarrigan** [comment]
Feel free to submit a PR!
