### ISSUE TITLE
[FEAT] Adding Daniel to the bot (he's left out from love :( )

### ISSUE THREAD

**Issue by Vyvy-vi** [nhcarrigan/we-love-hacktoberfest#38]
# Feature Request
Add Daniel to the bot too.

## Is your feature request related to a problem? Please describe:

Yah, the problem is that sometimes a few other people in the hacktoberfest team feel left out.
Even though all of them are lovely. (It's like we're playing favourites)

## Describe the solution you'd like:

I shall add Daniel to the bot and make a PR which maybe if you find satisfactory, can be used to create more love in the server for Daniel too

## Additional context:

you um stated in the server to make a pr.
![Screenshot 2020-10-20 at 12 35 55 AM](https://user-images.githubusercontent.com/62864373/96500272-3cc14880-126c-11eb-8b7c-9abeb9544711.png)

**Comment by nhcarrigan** [comment]
Open for contributions 😁
