### ISSUE TITLE
[FEAT] Adding phrases for 'hacktoberfest' keyword

### ISSUE THREAD

**Issue by Vyvy-vi** [nhcarrigan/we-love-hacktoberfest#45]
# Feature Request
Add responses for "hacktoberfest"

Yah, the problem is that sometimes a few other people in the hacktoberfest team feel left out.
Even though all of them are lovely. (It's like we're playing favourites)
Isn't it weird that the We-love-hacktoberfest bot doesn't have phrases for "hacktoberfest"

## Describe the solution you'd like

I shall add _hacktoberfest_ phrases to the bot and make a PR which maybe if you find satisfactory, can be used to create more love in the server for the rest of the team too

## Additional context
you um stated in the server to make a pr.
![Screenshot 2020-10-22 at 11 52 45 PM](https://user-images.githubusercontent.com/62864373/96913764-b4d47c00-14c1-11eb-91b2-c46d2b763651.png)

**Comment by Vyvy-vi** [comment]
Should I like add a role check instead of the id check and set checks for ppl with roles: 'helper', 'community manager', 'digitalOcean', 'vonage', 'Forem/dev', 'CircleCI', 'Raise.dev', 'Major League Hacking', 'JetBrains',' '...
or should I just remove the id checks...?

**Comment by nhcarrigan** [comment]
We still want the id checks as those determine if the author of a message is on the response list.

This should instead add a feature that checks for "hacktoberfest" in the message and responds with an appropriate phrase.
