### ISSUE TITLE
[OTHER] Change the PFP to HacktoberFest Logo

### ISSUE THREAD

**Issue by DeltaCoderr** [nhcarrigan/we-love-hacktoberfest#55]
# Other Issue

As we support Hacktoberfest, And the Bot's name was also changed. Why not change the profile Picture and keep it as the Hacktoberfest Logo itself? It would look neat.

**Comment by nhcarrigan** [comment]
To do that, and comply with the branding guidelines, we'd also need to include the partner logos.

**Comment by Vyvy-vi** [comment]
I don't think we could do that...
(Anf there isn't enough space for Including all the logos, without discord hiding them)

**Comment by nhcarrigan** [comment]
Yup. I think I'll close this for now.
