### ISSUE TITLE
[FEAT] - More names to add

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/we-love-hacktoberfest#56]
# Feature Request

## Is your feature request related to a problem? Please describe:

We need to add Paul.

Let's also add the helpers:
Walshy and Catbirby (and anyone else I am missing!)

## Describe the solution you'd like

Follow the same syntax as the other folks - verify the substring, call a phrase.

**Comment by Vyvy-vi** [comment]
Can I do this?
(since no one responded)

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by Vyvy-vi** [comment]
Oh wupps sorry for the late response... (totally forgot xD)
Making the pr 👍
