### ISSUE TITLE
[DOC] - Add Set Up Instructions

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/we-love-hacktoberfest#62]
# Incorrect Documentation

## Describe the error

The CONTRIBUTING.md file is missing the specific set up instructions for this project.

## Expected information

In the `Setting Up Your Code` section, we should add:

- Installing dependencies (`npm ci`)
- Building files (`npm run build`)
- Setting up Discord application
- Copying `sample.env` to `.env`
- Adding values to `.env`.
- Verifying lint (`npm run lint`)

**Comment by adityaraute** [comment]
`npm ci` installs dependencies? Why do I always use `npm install`. Are they any different?

**Comment by nhcarrigan** [comment]
`npm ci` bypasses the `package.json` and installs directly from the `package-lock.json`. It also asserts that the `package.json` and `package-lock.json` are in-sync, and throws an error if they are not (where `npm install` will re-write the `package-lock.json`). Finally, it clears any existing `node_modules` folder before installing.

**Comment by adityaraute** [comment]
Now I have seen that `package.json` and `package-lock.json` are two different files, but how. Anyway I should check on the internet probably 😂
